
export class RouterConstants {
  /**
   * home page url
   */
  static readonly HOME_PAGE_URL: string = 'pages/HomePage';


  /**
   * 基础组件
   */
  static readonly COMPONENTS_PAGE_URL: string = 'pages/components/ComponentsPage';
  /**
   * 目标管理
   */
  static readonly TARGET_MANAGEMENT_PAGE_URL: string = 'pages/targetmanagement/TargetManagementPage';
  /**
   * 简易视频播放
   */
  static readonly SIMPLE_VIDEO_PAGE_URL: string = 'pages/video/SimpleVideoPage';
  /**
   * 多种样式弹窗
   */
  static readonly MULTIPLE_DIALOG_PAGE_URL: string = 'pages/dialog/MultipleDialogPage';
  /**
   * 自顶一下拉动画
   */
  static readonly ANIMATE_REFRESH_PAGE_URL: string = 'pages/refresh/AnimateRefreshPage';
  /**
   * web组件
   */
  static readonly WEB_COMPONENT_PAGE_URL: string = 'pages/web/WebComponentPage';
  /**
   * 新闻数据加载
   */
  static readonly NEWS_DATA_PAGE_URL: string = 'pages/news/NewsDataPage';
  /**
   * 保存字体设置
   */
  static readonly SET_FONT_SIZE_PAGE_URL: string = 'pages/storage/SetFontSizePage';
  /**
   * 下载进度通知
   */
  static readonly DOWNLOAD_NOTIFICATION_PAGE_URL: string = 'pages/notification/DownloadNotificationPage';
  /**
   * 后台闹钟提醒
   */
  static readonly ALARM_CLOCK_PAGE_URL: string = 'pages/clock/AlarmClockPage';
  static readonly DETAIL_CLOCK_PAGE_URL: string = 'pages/clock/DetailIndex';


  /**
   * SplashScreen Page Url
   */
  static readonly SPLASH_SCREEN_PAGE_URL: string = 'SplashScreenPage';


  /**
   * Login page url
   */
  static readonly LOGIN_PAGE_URL: string = 'pages/login/LoginPage';

  /**
   * Mine page url.
   */
  static readonly MINE_PAGE_URL: string = 'pages/login/MinePage';


  /**
   * Registration success page url.
   */
  static readonly REGISTRATION_SUCCESS_PAGE_URL: string = 'pages/login/RegistrationSuccessPage';

  /**
   * Privacy page url.
   */
  static readonly PRIVACY_PAGE_URL: string = 'pages/login/PrivacyPage';

  /**
   * Customer service page url.
   */
  static readonly CUSTOMER_SERVICE_PAGE_URL: string = 'pages/login/CustomerServicePage';





  /**
   * About page url.
   */
  static readonly ABOUT_PAGE: string = 'pages/about/AboutPage';

  /**
   * Agreement page url.
   */
  static readonly AGREEMENT_PAGE: string = 'pages/about/AgreementPage';

  /**
   * Detail page url.
   */
  static readonly DETAIL_PAGE = 'pages/about/DetailPage';

  /**
   * Business Card page url.
   */
  static readonly BUSINESS_CARD_PAGE = 'pages/business/BusinessCardPage';

  /**
   * Category page url.
   */
  static readonly CATEGORY_PAGE = 'pages/category/CategoryPage';
}